# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"validate_layers": "00_main.ipynb",
         "cli": "00_main.ipynb",
         "device": "01_config.ipynb",
         "imsize": "01_config.ipynb",
         "normalization_mean": "01_config.ipynb",
         "normalization_std": "01_config.ipynb",
         "content_layers_default": "01_config.ipynb",
         "style_layers_default": "01_config.ipynb",
         "ContentLoss": "02_nst.ipynb",
         "gram_matrix": "02_nst.ipynb",
         "StyleLoss": "02_nst.ipynb",
         "Normalization": "02_nst.ipynb",
         "get_style_model_and_losses": "02_nst.ipynb",
         "get_input_optimizer": "02_nst.ipynb",
         "run_style_transfer": "02_nst.ipynb",
         "image_loader": "03_util.ipynb",
         "image_unloader": "03_util.ipynb",
         "imshow": "03_util.ipynb",
         "show_all_images": "03_util.ipynb",
         "save_image": "03_util.ipynb",
         "random_img": "03_util.ipynb",
         "loader": "03_util.ipynb",
         "unloader": "03_util.ipynb"}

modules = ["main.py",
           "config.py",
           "nst.py",
           "util.py"]

doc_url = "https://tomsitter.github.io/pytorch_nst/"

git_url = "https://github.com/tomsitter/pytorch_nst/tree/master/"

def custom_doc_links(name): return None
