# AUTOGENERATED! DO NOT EDIT! File to edit: 01_config.ipynb (unless otherwise specified).

__all__ = ['device', 'imsize', 'normalization_mean', 'normalization_std', 'content_layers_default',
           'style_layers_default']

# Cell
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
imsize = 512 if torch.cuda.is_available() else 128

# VGG network was trained on normalized images, so must do the same to ours
normalization_mean = torch.tensor([[0.485, 0.456, 0.406]]).to(device)
normalization_std = torch.tensor([[0.229, 0.224, 0.225]]).to(device)

content_layers_default = ['conv4_2']
style_layers_default = ['conv1_1', 'conv2_1', 'conv3_1', 'conv4_1', 'conv5_1']